[project]
name = "llm-from-scratch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "pandas>=3.0.5",
    "tiktoken>=0.14.0",
    "torch>=2.14.0",
    "tqdm>=4.70.1",
]

[project.scripts]
llm-from-scratch = "llm_from_scratch:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
    "jupyterlab>=4.6.3",
    "ruff>=0.16.7",
]
test = [
    "pytest>=8.4.2",
]
viz = [
    "flask>=3.1.0",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
